name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clean old build on server
      run: |
        ssh -o StrictHostKeyChecking=no enz@h3015104.stratoserver.net 'rm -rf /home/enz/www/staging.einfachnurzocken.com/einfachnurzocken/build/*'

    - name: Sync new build files to server
      run: |
        rsync -avz --delete \
        -e "ssh -o StrictHostKeyChecking=no" \
        ./build/ enz@h3015104.stratoserver.net:/home/enz/www/staging.einfachnurzocken.com/einfachnurzocken/build/

    - name: Restart Apache
      run: |
        ssh -o StrictHostKeyChecking=no enz@staging.einfachnurzocken.com 'sudo systemctl restart apache2'